//---------------------------------------------------------
//-- File generated by RobustVerilog parser
//-- Version: 1.0
//-- Invoked Fri Mar 25 23:34:50 2011
//--
//-- Source file: dma_defines.v
//---------------------------------------------------------


  
`define FRAME_BITS     12
`define X_BITS         8
`define TOKEN_BITS     6
`define OUT_BITS       4
`define DELAY_BITS     3
`define CMD_CNT_BITS   12
`define INT_CNT_BITS   4
`define WAIT_BITS      12
`define TIMEOUT_BITS   10
`define WDT_BITS       11
`define CMD_BITS       7
`define ID_BITS        1
`define LEN_BITS       4
`define SIZE_BITS      2

`define ID_END_LINE    6
`define ID_LAST        3




