//---------------------------------------------------------
//-- File generated by RobustVerilog parser
//-- Version: 1.0
//-- Invoked Fri Mar 25 23:34:53 2011
//--
//-- Source file: dma_ch_reg_params.v
//---------------------------------------------------------


  
   parameter              CMD_LINE0      = 8'h00;
   parameter              CMD_LINE1      = 8'h04;
   parameter              CMD_LINE2      = 8'h08;
   parameter              CMD_LINE3      = 8'h0C;
   parameter              STATIC_LINE0   = 8'h10;
   parameter              STATIC_LINE1   = 8'h14;
   parameter              STATIC_LINE2   = 8'h18;
   parameter              STATIC_LINE3   = 8'h1C;
   parameter              STATIC_LINE4   = 8'h20;
   
   parameter              RESTRICT       = 8'h2C;
   parameter              RD_OFFSETS     = 8'h30;
   parameter              WR_OFFSETS     = 8'h34;
   parameter              FIFO_FULLNESS  = 8'h38;
   parameter              CMD_OUTS       = 8'h3C;
   
   parameter              CH_ENABLE      = 8'h40;
   parameter              CH_START       = 8'h44;
   parameter              CH_ACTIVE      = 8'h48;
   parameter              CH_CMD_COUNTER = 8'h50;
                 
   parameter               INT_RAWSTAT    = 8'hA0;
   parameter               INT_CLEAR      = 8'hA4;
   parameter               INT_ENABLE     = 8'hA8;
   parameter               INT_STATUS     = 8'hAC;


